name: atlasgemini
favicon: null
layout_spectrum: 0.22791790217161179
typography_spectrum: 0.3622888131067157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dcdddd'
    - '#afafb0'
    - '#818283'
    - '#545557'
  brandStrength: 0.8659970201551914
  lightness: 0.7561266508419067
  saturation: 0.059746789978817105
  rhythmicContrast: 0.28704825788736343
purpose: []
